### DISCUSSION TITLE
rgd.yml

### DISCUSSION THREAD

**Discussion by eryajf** [awesome-ops/awesome-ops.github.io#1] [General]
```
owner: awesome-ops
repo: awesome-ops.github.io
type: issues
issues-owner: awesome-ops
issues-repo: awesome-ops.github.io

website:
  logo: https://avatars.githubusercontent.com/awesome-ops
  title: Awesome-Ops
  description: 认清不足，认识优秀，认知提升，共同成长。
  home: issues-labels
  home-layout: [label]
  label-category: [CMDB,CICD,K8S-Cluster-Manage,Docker-Tools,运维管理平台,更多]
  label-level: [L1, L2, L3, L4]
  built-date: 2025

manifest:
  name: Awesome-Ops
  short_name: Awesome-Ops
  start_url: /
  background_color: "#654FF0"
  theme_color: "#FFFFFF"
  display: standalone
  icon: https://avatars.githubusercontent.com/awesome-ops
```
